module.exports = {
    COLLECTION_USERS: 'users',
    FIELD_EMAIL: 'email',
    FIELD_PASSWORD: 'password',
    FIELD_NAME: 'name',
    FIELD_ID: 'id',
    COLLECTION_USER_AUTHENTICATION: 'user_authentication',
    FIELD_EXPIRES_ON: 'expires_on',
    COLLECTION_PRODUCT: 'product', 
    FIELD_DESCRIPTION: 'description',
    FIELD_PRICE: 'price',
    FIELD_CATEGORY: 'category',
    FIELD_USER_CODE: 'user_code',
    COLLECTION_CART: 'cart',
    COLLECTION_MENU: 'menu',
    COLLECTION_ORDER: 'order',
    FIELD_USER_ID: 'user_id',
    FIELD_ORDER_INFO: 'order_info',
    FIELD_TOTAL: 'total',
    COLLECTION_RATINGS: 'ratings',
    FIELD_ORDER_ID: 'order_id',
    FIELD_RATING: 'rating'
}